kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: log-aggregator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: log-aggregator
subjects:
  - kind: ServiceAccount
    name: log-aggregator
    namespace: prow
