kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: log-aggregator
rules:
  - apiGroups:
      - tekton.dev
      - prow.k8s.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
    verbs:
      - "get"
