kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: test-infra
  name: log-aggregator
rules:
- apiGroups:
  - tekton.dev
  - prow.k8s.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
{{- if not .Values.podSecurityStandards.enforced }}
- apiGroups:
  - policy
  resourceNames:
  - privileged
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
