apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prow
  name: log-aggregator
  labels:
    app: log-aggregator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-aggregator
  template:
    metadata:
      labels:
        app: log-aggregator
    spec:
      serviceAccountName: log-aggregator
      containers:
        - name: log-aggregator
          image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          args:
            - --namespace=nightly
