apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-infra
  name: log-aggregator
  labels:
    app: log-aggregator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-aggregator
  template:
    metadata:
      labels:
        app: log-aggregator
    spec:
      serviceAccountName: log-aggregator
      containers:
        - name: log-aggregator
          image: "{{ .Values.Installation.V1.Registry.Domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          args:
            - daemon
            - --kubeconfig.namespace={{ .Values.kubeconfig.namespace }}
            - --server.listen.address=http://0.0.0.0:8000
      securityContext:
        runAsUser: 1000
        allowPrivileveEscalation: false
        seccompProfile:
          type: RuntimeDefault
