apiVersion: v1
kind: Service
metadata:
  name: log-aggregator
  namespace: prow
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: log-aggregator
  type: ClusterIP
