apiVersion: v1
kind: Service
metadata:
  name: log-aggregator
  namespace: test-infra
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  ports:
  - port: 8000
  selector:
    app: log-aggregator
  type: ClusterIP
