kubeconfig:
  namespace: "test-workloads"
image:
  name: "giantswarm/prow-log-aggregator"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

securityContext: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  allowPrivilegeEscalation: false
  seccompProfile:
    type: RuntimeDefault
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true

global:
  podSecurityStandards:
    enforced: false
