kubeconfig:
  namespace: "test-workloads"
image:
  name: "giantswarm/prow-log-aggregator"
  tag: "[[ .Version ]]"
Installation:
  V1:
    Registry:
      Domain: quay.io
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

global:
  podSecurityStandards:
    enforced: false
