version: 2.1

orbs:
  architect: giantswarm/architect@0.10.2

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: prow-log-aggregator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          image: "quay.io/giantswarm/prow-log-aggregator"
          context: architect
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
