version: 2.1

orbs:
  architect: giantswarm/architect@0.10.2

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: prow-log-aggregator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          image: "quay.io/giantswarm/prow-log-aggregator"
          context: architect
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      # Ensure that for every commit to master and for every
      # release tag, there is an app version in the catalog.
      - architect/push-to-app-catalog:
          name: push-to-app-catalog-master
          app_catalog: "conformance-catalog"
          app_catalog_test: "conformance-test-catalog"
          chart: "prow-log-aggregator"
          context: architect
          requires:
            - push-to-quay
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/

      # Ensure that for every commit (branch other than master)
      # there is an app version in the test catalog.
      - architect/push-to-app-catalog:
          name: push-to-app-catalog-pr
          app_catalog: "conformance-catalog"
          app_catalog_test: "conformance-test-catalog"
          chart: "prow-log-aggregator"
          context: architect
          requires:
            - push-to-quay
          filters:
            branches:
              ignore: master
