version: 2.1

orbs:
  architect: giantswarm/architect@2.2.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: prow-log-aggregator
          resource_class: large
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          context: architect
          image: "quay.io/giantswarm/prow-log-aggregator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-app-catalog-master
          context: architect
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "prow-log-aggregator"
          requires:
            - push-to-quay
          filters:
            tags:
              only: /^v.*/
